<a href="https://colab.research.google.com/github/thalisreboucas/Python-codes-ML/blob/main/Basico_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Comandos Basicos do Python**

In [ ]:
#Definir uma variavel
x= 5
#para ver x você tem que printar ou seja , usar a função print().
print(x)

#Qual o tipo de variavel x
type(x)

#Variavel string

y= 'a'  #Sempre que for uma varaivel é string obrigatoriamente ao definir essa variavel é nescessario utlizar as aspas("")

print(y,type(y))

#Temos como qualquer outra linguagem de programação os tipos de variaveis,podendo ser "int" ,nesse caso um número inteiro,"float",nesse caso uma 
#varaivel de ponto flutuante ou seja um varaivel real, "string" , ou seja uma varaivel de caracteres.

#Temos tambem as varaiveis "list" , "tuple" e "dic"


5
a <class 'str'>


In [ ]:
#Criando uma lista 
x=[1,2,3,4,5]
print(x)
type(x)

#Tamanho da Lista, usa-se o comando ,len().
print(len(x))

#Valor maximo de uma número na list usa-se , max().
print(max(x))

#Valor minimo de uma número na list usa-se , min().
print(min(x))

#Manipulação de listas
y = [6,7,8,9,10]

#Adiciona um valor ou mais a uma lista, list.append(valor ou variavel).
y.append(1)
y.append(x)
print(y)

#inserir o valor em uma espaço definido, utiliza o comando list.insert(posição,variavel/valor).
#Lembrando que o a primeira posição é zero
y.insert(0,5) 
print(y)

#Para contar algum valor ou caractere na lista, list.count(valor).
y.count(1)

#Remover valores de uma lista , list.remove().
y.remove(1)
y.remove(x)

print(y)

#Para organizar um lista , temos o comando , list.sort().
z=[1,3,2,6,5,8]

print(z)

#Agora organizando a lista em ordem cresente utiliza , reverse=False.
z.sort(reverse= False)
print(z)

#Agora organizando a lista em ordem decresente utiliza , reverse=True ou list.reverse().
z.sort(reverse= True)

print(z)

#Ver um valor especifico da lista list[posição]
z[2]


[1, 2, 3, 4, 5]
5
5
1
[6, 7, 8, 9, 10, 1, [1, 2, 3, 4, 5]]
[5, 6, 7, 8, 9, 10, 1, [1, 2, 3, 4, 5]]
[5, 6, 7, 8, 9, 10]
[1, 3, 2, 6, 5, 8]
[1, 2, 3, 5, 6, 8]
[8, 6, 5, 3, 2, 1]


5

In [ ]:
#Operações com Listas 
#Definindo duas listas
A = [0,2,4]
B = [6,8,10]
#"Somar" duas listas 
C = A+B

print(C) #como podemos ver esse comando junta duas listas

#Repetir a lista n vezes , list*n
D = A*2

print(D)

#Saber se um objeto pertence a lista

3 in A



[0, 2, 4, 6, 8, 10]
[0, 2, 4, 0, 2, 4]


False

In [ ]:
#Crinado um tuple
x = (1,2,3,4,5)
print(x)

type(x)

#Comandos para Tuple

#Tamanho de um Tuple, usa-se o comando ,len().
print(len(x))

#Valor maximo de uma número na Tuple usa-se , max().
print(max(x))

#Valor minimo de uma número na Tuple usa-se , min().
print(min(x))

#os comandos são o mesmo das listas

(1, 2, 3, 4, 5)
5
5
1
(1, 2, 3, 4, 5, 2, 3, 4, 5)


In [ ]:
#Strings 
x = 'Meu nome'
print(x)

#comando input(),serve para receber um objeto .
y = input("Digite seu nome")
print(y)

z = input("Digite sua idade")
print(z)

print('Meu nome é ',y,'e tenho',z ,'anos de idade')


Meu nome
Digite seu nomeThalis
Thalis
Digite sua idadeRebouças
Rebouças
Meu nome é  Thalis e tenho Rebouças anos de idade


**Condicionais e Estrutura**

Python suporta **três codigos** para controle de estrutura : **if, while, and for**

> **Estrutura If**


O "if" é um paramentro de condição , que é a condição "se" ,dentro dessa estrutura temos o "else"que é o comando "se não" ,caso exista mais de condições pode usar o "elif" que é o "else + if " , que também é um "se não" , mas é para caso haja varias condições.



> **Exemplo do If**  .



```
a=1
b=2
c=5
if a > b :
  print('a é maior que b')
elif a > c :
  print('a é maior que c')
else:
    print('b é maior que a')
```









In [ ]:
a=1
b=2
c=5
if a > b :
  print('a é maior que b')
elif a > c :
  print('a é maior que c')
else:
    print('b é maior que a')



**Estrutura While**

Essa é uma estrutura para criar loops, neste caso o "while" é o comando "enquanto". Um dos cuidados que temos que ter é que o While precisa de uma condição para termina o "equanto" se não ficará em um looping infinito.



> **Exemplo do While**



```
Idade = 0 
while(Idade < 90):
  print('A idade é ',Idade)
  Idade = Idade + 1
print('Finalizou o While')
```




In [ ]:
Idade = 0 
while(Idade < 90):
  print('São idade menos que noventa : ',Idade,'Anos')
  Idade = Idade + 1 #serve para finalizar o looping ,pois se não só imprimiria o valor 0
print('Finalizou o While')

**Estrutura For**

O "For" é uma estrutura de loop que "anda" em cima de algumas tipos de variavéis em sequência como , "list", "string" e "dictionary". O "For" é a estrutura "para".



> **Exemplo do For**



```
bolas = [ 1,2,3,4,5,6,6,7,8,8,9,10,60,61,62,63]

for numero in bolas :
  if numero == 4 :
   print('Saiu a bola é a 4')
  elif numero == 62 :
   print('Saiu a bola é a 62')
  else:
   print('Bola que não saiu')
```



In [ ]:
bolas = range(1,11)
#range funciona criando uma lista de números ,range(x,y,n) ,sendo x o número que começa a lista e y o número que irá termina a lista, e n caso queria fazer a lista pulando em n em n .

for numero in bolas :
  if numero == 1 :
   print('Saiu a bola é a 1')
  elif numero == 2 :
   print('Saiu a bola é a 2')
  else:
   print('Bola que não saiu')



#Podemos também fazer com strings
for x in 'bola':
  print(x)


**Programação orientada a Objetos**

É um paradigma de programação baseado no conceito de "objetos", que podem conter dados na forma de campos, também conhecidos como atributos, e códigos, na forma de procedimentos, também conhecidos como métodos.

> **Class**


Temos a 'class' que define um atribudo a dados comuns e metodos para funções para um objeto. O termo 'class' , classes em português é um conceito abstrato. Um programa objeto orientado pode possuir multiplas classes. 

> **Objects**

Um objeto é uma instacia de uma classe. É o que vai receber e guadar o atual tipo de dado e seu valor atribuido e vão chamar o metodo, podemos ter sub-classes de objetos também.

O objeto pode representar várias coisas do nosso mundo , como uma imagem,video,base de dados , etc.




**Expreção Regulares e manipulação de arquivos**


Expreção Regulares são como se fosse mini-liguagem definida dentro da linguagem usadas para manipular/definida regras especificas para strings definidas pelo programador .

Expreção Regulares são usadas em diferentes tarefas como :

*   Dividir ou mudar strings
*   Encontrar uma sentença 
* Pré processamento de texto 
* Indetificar numeros ou outros simbolos

É importante saber saber usar a sintaxes apropriadas como :


*   Usar os simbolos . ^$+?[]{}\|()
*   [0-9]
*   [a-z]
*   a{4}


> **Exemplo**



```
Import re #importante importa a library re no python 

texto_para_encotrar = "sou um programador"

pattern = re.compile (r'sou') 

match = pattern.match(texto_para_encotrar)

if match :
  print(match.group())
```

**R.E modulo de funções**

* match -> Encontrar um expreção regular padrão para o inicio do string
* fullmatch -> Encontrar um expreção regular padrão para toda a string
* search -> procurar um r.e padrão para toda a string
* sub -> para substituir a ocorrencia de um padrão em uma string
* split -> dividir uma string pela a ocorrencia de padrões 
* compile -> compilar um padrão em uma objeto padrão 

entre outros ,pode acessar o [r.e no python ](https://pymotw.com/2/re/) para entender melhor.





In [ ]:
import re 
#importante importa a library re no python 

texto_para_encotrar = "sou um programador"

pattern = re.compile (r'sou') 
padrao = re.compile (r'Programador')

match = pattern.match(texto_para_encotrar)


if match :
  print(match.group())


sou


**Acessar arquivos no Python**

Uma arquivo pode ser acessada com seguindo as seguides funções.

* 'w' -> cria um novo arquivo apenas para escrever ou sobescrever um aquirvo que já existe.
* 'r' -> ler um arquivo 
* 'a' -> Abri um arquivo para escreve-lo, caso não haja um arquivo para escrever

* 'w+','r+','a+' , criação de arquivos para ler e escrever ,sendo respectivamente para criar um novo arquivo, abrir um novo arquivo  e abrir um arquivo já existente.


> **Exemplo**

```
#Ler arquivo

f = open('filename.txt','r')
linhas = f.readlines()
for linha in linhas:
  print(linhas)
f.close()

#Escrever arquivo

f =  open('filename.txt','w')
f.write('hello world\n!')
f.close()

```



# **Algebra Linear**

> **Revisão**

As matrizes representação tansformações lineares em espaços vetorias, um espaço vetorial possui varias coodernadas.
Transformações lineares são funções com vetores de entrada e saida.

```
Eg.v' = Mv
```
O vetor v é a transformação da matriz M resultando no vetor v'.


---


> **Composição de Matrizes**

A composição de matrizes descrevem o efeito de multiplicação e transformações .

> Eg,v' = ABv

A operação  de multiplicação entre as matrizes A,B  é a matriz de composição .

Função rotação : Esquerda e Direta. 

*  A multiplicações de matrizes não são comutativas 
*  A multiplicação de matrizes são associativas.



---


> **Operações Lineares**

A multiplicação de um vetor V_nxc pela uma matriz M_mxn ,resulta no caso geral de  :  

> v'_mxc = M_mxn.v_nxc

> **Determinante** 
O determinate é uma variavel escalar que representa o quanto que o espaço vetorial foi modificado por uma transformação.

* Det(M) > 1, A area aumenta. 
* Det(M) < 1, A area diminui.
* Det(M) = 0, Mostra que a diminuição do espaço vetorial em um menor.










# **Algebra no Python**

Para fazer calculos de matrizes no Python teremos que utilizar a blibioteca numpy , que tem varias funções matematicas e operações com matrizes .

> Referencia API [Numpy Python](https://numpy.org/doc/stable/user/quickstart.html)

> Referencia [Cheat sheets](https://www.datacamp.com/community/blog/python-numpy-cheat-sheet)

Você pode instalar o usando o comando :


```
pip3 install numpy

import numpy as np
```


Alguns tipos de variaveis que nos esperamos trabalhar no numpy.
* bool
* int_
* float_
* complex_



```
bold = True
int = 10
float = 3.0
complex = 1+2x
```
> **Criando um vetor**

A criação de vetor segue a seguite linha de codigo, sendo que o dados presentes podendo ser inteiros ou reais e também matrizes de multiplas dimensões.



```
import numpy as np

vetor =np.array([[1,2,3]])

#criando vetor real com type float

vetor_2 =np.array([[1,2,3]],dtype=np.float_)

# criando matriz de multiplas dimensões

vetor_3 =np.array([[1,2],[3,4]])

```




In [ ]:
import numpy as np

vetor =np.array([[1,2,3]])

print(vetor)
#criando vetor real com type float

vetor_2 =np.array([[1,2,3]],dtype=np.float_)
print(vetor_2)

# criando matriz de multiplas dimensões

vetor_3 =np.array([[1,2],[3,4]])

print(vetor_3)

[[1 2 3]]
[[1. 2. 3.]]
[[1 2]
 [3 4]]


> **Matriz indentidade**

A matriz indentidade é a que tem a diagonal principal igual a 1, e é criado pelo comando np.eye(x), sendo x um número inteiro.

```
import numpy as pd

ind = np.eye(4)

```


In [ ]:
import numpy as np

ind = np.eye(4)
print(ind)

>**Operações e funções**
  Dado uma matriz m de 3 dimensões 

```
import numpy as np

M = np.array([[1,2,3],[4,5,6],[7,8,9]])

```
  * M[0] Seleciona a primeira linha
  * M[1,2] Seleciona a segunda linha e o terceiro elemento
  * M[:] Seleciona todos os elementos da matriz
  * M[:,0] Seleciona a primeira coluna
  * M[:,:2] Seleciona as duas primeiras colunas
  * M[:,1:3] Seleciona as duas ultimas colunas



In [ ]:
import numpy as np
 
M = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(M[0])
print(M[1,2])
print(M[:])
print(M[:,0])
print(M[:,:2])
print(M[:,1:3])

> **Multiplição,soma ,subtração , divisão , transposta**


*   Produto utiliza o operador : *
*   Soma utiliza o operador : +
*   Subtração utiliza o operador : -
*   Divisão utiliza o operador : /
*   Transposta utiliza o operador : .T
*  Multiplicação utiliza o operador : @



```
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,0,0],[0,5,0],[0,0,9]])

print(A*B)

print(A+B)

print(A.T)
```







In [ ]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,0,0],[0,5,0],[0,0,9]])

print(A*B)

print(A+B)

print(A.T)

print(A@B)

#Bônus: Produto vetorial 
x = np.array([[1,2,3]])
y = np.array([[1,0,1]])

z = np.cross(x,y)
print(z)


#**Decomposição e fatoração de Matrizes**


> **Introdução a decomposição de matrizes**

A a decomposição de matriz , também conhecido como fatoriazação , nada mas é que transformar as matrizes em produtos de matrizes ,assim otimizando a solução de sistemas. facilindado achar os auto valores e auto vetores.


---


> **Decomposição L.U**

Uma matiz A é transformada em uma matriz L é uma matiz triangular inferior e na qual a diagonal principal é 1 e U é uma matriz triagunlar diagonal superior 


---


> **Decomposição em QR**

Uma matriz A é tranformarda em uma matriz Q ortogonal e R é uma matriz superior triangular ,nessa decomposição a matriz A não precisar ser nescessáriamente quadrada. 
Essa decomposição é uma aplicação de SVD e minimos quadrados.


---


> **Decomposição em SVD**

É uma decomposição em valores singulares,sendo a decomposição em eign valores e vetores de uma Matriz A,que pode não pode ser quadradas. 
Essa decomposição transformar a matriz A em três valores sendo U e V matrizes ortogonais sendo chamada matriz esquerda e direita , temos a matriz D que é a diagonal positiva que tem números reais sendo os valores singulares 




---

>**Aplicação**

Temos LLS e PCA

#**Machine Learning**

Machine learnig nada mais é do que o estudo dos algoritimos de apredizagem com dados.

Um computador é capaz de aprender tarefas e executa-las através de experiencia e melhorar o seu desempenho.

Temos os algoritimos de :


*   Clasificação
*   Regressão
*  Clusterização






#**Rede Neurais**

In [ ]:
import pandas as pd
import numpy as np

A = np.array([[4,0,0],[-3,8,3],[0,0,12]])
print(A)
B = np.array([[4,0,0,96],[-3,8,3,192],[0,0,12,96]])
print(B)

np.linalg.eig(A)


def f(x):

  return x**2 - x - 1


N,a,b = 4,1,2

for n in range(1,N+1):

  m_n = (a + b)/2

  f_m_n = f(m_n)

  if f(a)*f_m_n < 0:

    b = m_n

  else:

    a = m_n

x= (a + b)/2

print(x)




[[ 4  0  0]
 [-3  8  3]
 [ 0  0 12]]
[[  4   0   0  96]
 [ -3   8   3 192]
 [  0   0  12  96]]
1.59375


In [ ]:
from statistics import variance

data = [2.75, 1.75, 1.25, 0.25]

x = variance(data)
print(x)

1.0833333333333333
